image: node:5.0.0-slim
git:
  path: github.com/hushaoping/service1
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/hushaoping/service1
build:
  image: node:5.0.0-slim
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
